### ISSUE TITLE
Issue when deploying with arm template

### ISSUE THREAD

**Issue by leolorenzoluis** [cmilanf/docker#1]
Hello,

Thanks for creating the arm templates. However, there is an issue when you deploy for MySQL. Gen4 is no longer supported.

**Comment by cmilanf** [comment]
Thanks for the notification! I updated the template in the new repository at [https://github.com/cmilanf/docker-ghostazurewebapplinux](https://github.com/cmilanf/docker-ghostazurewebapplinux)
