### ISSUE TITLE
Issue with 2.13.1

### ISSUE THREAD

**Issue by leolorenzoluis** [cmilanf/docker#2]
Not sure if this is from your image but when trying to access the settings to inject Blog Header. The text box is disabled, the only available input is for Blog Footer.

**Comment by cmilanf** [comment]
It is working rightly on my blog. Please, make sure you are using the new repository image that you can find at [https://github.com/cmilanf/docker-ghostazurewebapplinux](https://github.com/cmilanf/docker-ghostazurewebapplinux). Report anything related to Ghost blog there and sorry for the inconvenience.
